#Show all vulnerabilities, clusters exposed to it and when it happened first

prefix :<http://application-inventory/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

select ?v ?c (MIN(?d) as ?introducedAt) 
where {
    << ?a :deployedTo ?c >> :deployedOn ?d .
    ?v :exposedIn ?p .
    ?p :includedIn ?a .   
}
group by ?v ?c


#Insert new host
prefix :<http://application-inventory/>

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

insert data {
    :new-cluster rdf:type :Host ;
        :name "New cluster"^^xsd:string ;
        :description "New cluster"^^xsd:string .
}

#delete new host
prefix :<http://application-inventory/>

DELETE WHERE { ?object :name 'New cluster' ;
                       ?property      ?value }
