apiVersion: apps/v1
kind: Deployment
metadata:
  name: workbench
  labels:
    app: workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workbench
  template:
    metadata:
      labels:
        app: workbench
    spec:
      containers:
      - name: workbench
        image: ontotext/platform-workbench:4.0.3
        ports:
        - containerPort: 3000
        env:
        - name: SOAAS_ENDPOINT
          value: "http://semantic-objects:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: workbench
  labels:
    app: workbench
spec:
  selector:
    app: workbench
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
